name: Deploy to Private EC2

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add Private EC2 Host Key
        run: |
          ssh-keyscan -H 172.31.26.234 >> ~/.ssh/known_hosts

      - name: Test Connectivity
        run: |
          ping -c 4 172.31.26.234

      - name: Connect to Private EC2
        run: |
          ssh -i ~/.ssh/id_rsa \
            -o StrictHostKeyChecking=yes \
            ec2-user@172.31.26.234 << 'EOF'
            echo "Connected Successfully"
            hostname
            whoami
            pwd
            ls -la
          EOF
